### ISSUE TITLE
H5 and H6 are unreadable

### ISSUE THREAD

**Issue by ghost** [fmaida/mkdocs-material-dark-theme#5]
In the default CSS there is the following line.

```css
.md-typeset h5, .md-typeset h6 {
    color: rgba(0,0,0,.54);
    font-size: .64rem;
}
```

This is black on grey which doesn't look good.

![image](https://user-images.githubusercontent.com/65161626/81928595-cbf37180-95e5-11ea-80d0-8d710575a8bc.png)

I applied the following fix, maybe you can integrate that in your scss?

```css
.md-typeset h5, .md-typeset h6 {
    color: inherit;
}
```

That way the color from body (and thus all other headings) is used which is some light grey.
