### ISSUE TITLE
Suggestion for <kbd>

### ISSUE THREAD

**Issue by ghost** [fmaida/mkdocs-material-dark-theme#6]
We had a weird glitch where `<kbd>` elements didn't render properly. But since your theme didn't modify `<kbd>` at all I adapted the style from stackoverflow, maybe you want to integrate that into your SCSS?

```css
.md-typeset kbd {
    box-shadow: 0 1px 2px rgba(12,13,14,0.75);
    display: inline-block;
    margin: 0 .1em;
    padding: .1em .6em;
    font-size: 11px;
    line-height: 1.4;
    color: #e7e8eb;
    text-shadow: 0 1px 0 #2d2d2d;
    background-color: #404345;
    border: 1px solid #7d848d;
    border-radius: 2px;
    white-space: nowrap;
}
```

which looks like

![image](https://user-images.githubusercontent.com/65161626/81929284-11fd0500-95e7-11ea-86db-ef87fc02f4de.png)
